#!/usr/bin/env python3
"""
arc_cookie_export.py — Export Arc browser cookies to Netscape cookie format.

The Problem:
  Arc stores its cookie encryption key in macOS Keychain under "Arc Safe Storage",
  not "Chrome Safe Storage". yt-dlp's --cookies-from-browser chrome always uses
  Chrome's key, causing 1400+ Arc cookies (including LOGIN_INFO, SAPISID, SID)
  to fail silently — stripping Premium authentication from the exported file.

The Fix:
  Monkey-patch yt-dlp's browser settings to use the 'Arc' keyring name so it
  looks up "Arc Safe Storage" in Keychain instead of "Chrome Safe Storage".

Usage: python3 arc_cookie_export.py <output_cookies.txt> [profile_dir]
"""

import sys
from pathlib import Path


ARC_PROFILE_DIRS = [
    Path.home() / "Library/Application Support/Arc/User Data/Default",
    Path.home() / "Library/Application Support/Arc/User Data/Profile 1",
    Path.home() / "Library/Application Support/Arc/User Data/Profile 2",
]


def find_best_profile() -> Path:
    for p in ARC_PROFILE_DIRS:
        if (p / "Cookies").exists():
            return p
    raise FileNotFoundError("No Arc profile with a Cookies database found")


def export_arc_cookies(output_path: Path, profile_dir: Path) -> tuple[int, int]:
    """
    Use yt-dlp's cookie extraction with Arc's correct Keychain key.
    Returns (total_cookies, youtube_cookies).
    """
    import http.cookiejar
    import yt_dlp.cookies as ytcookies
    from yt_dlp.cookies import extract_cookies_from_browser, YDLLogger

    # Patch _get_chromium_based_browser_settings to return Arc's keyring name.
    # This makes _get_mac_keyring_password look up "Arc Safe Storage" in Keychain
    # instead of "Chrome Safe Storage", enabling correct decryption of Arc cookies.
    orig_settings = ytcookies._get_chromium_based_browser_settings

    def patched_settings(browser_name):
        settings = orig_settings(browser_name)
        if browser_name == "chrome":
            settings = dict(settings)
            settings["keyring_name"] = "Arc"
            settings["browser_dir"] = str(profile_dir)
        return settings

    ytcookies._get_chromium_based_browser_settings = patched_settings
    try:
        jar = extract_cookies_from_browser("chrome", str(profile_dir), YDLLogger())
    finally:
        ytcookies._get_chromium_based_browser_settings = orig_settings

    # Serialize to Netscape HTTP Cookie File format
    lines = ["# Netscape HTTP Cookie File\n# Generated by arc_cookie_export.py\n\n"]
    total = 0
    for cookie in jar:
        total += 1
        host = cookie.domain
        include_subdomains = "TRUE" if host.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.secure else "FALSE"
        expiry = int(cookie.expires) if cookie.expires else 0
        lines.append(
            f"{host}\t{include_subdomains}\t{cookie.path}\t{secure}\t"
            f"{expiry}\t{cookie.name}\t{cookie.value}\n"
        )

    output_path.write_text("".join(lines), encoding="utf-8")
    yt_count = sum(1 for l in lines if "youtube.com" in l)
    return total, yt_count


if __name__ == "__main__":
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("cookies.txt")
    profile = Path(sys.argv[2]) if len(sys.argv) > 2 else find_best_profile()

    print(f"Profile : {profile}", flush=True)
    print(f"Output  : {output}", flush=True)

    try:
        total, yt_count = export_arc_cookies(output, profile)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Exported: {total} cookies ({yt_count} youtube.com)", flush=True)
    if total == 0:
        sys.exit(1)
